# Generated by Django 4.0.6 on 2022-07-23 13:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(choices=[('shampoo', '샴푸'), ('black_powder', '흑채'), ('wig', '가발'), ('hairbeam', '헤어빔')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('deli_fee', models.PositiveIntegerField()),
                ('rocket', models.BooleanField(default=False)),
                ('pay_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('youtube_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('use_period', models.CharField(blank=True, max_length=100, null=True)),
                ('how_to_use', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('coo', django_countries.fields.CountryField(max_length=2)),
                ('cosmetic_component', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('precaution', models.TextField(blank=True, null=True)),
                ('quality_guarantee', models.CharField(blank=True, max_length=100, null=True)),
                ('item_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about_electric', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('inquiry_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='items.item')),
            ],
        ),
    ]
