# Generated by Django 4.0.6 on 2022-07-26 14:03

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetailpage',
            name='photo',
            field=models.ImageField(upload_to=items.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(upload_to=items.models.path_and_rename),
        ),
    ]
