# Generated by Django 4.0.6 on 2022-07-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deli_number', models.CharField(max_length=50)),
                ('deli_code', models.CharField(max_length=3)),
                ('done', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='payments.payment')),
            ],
        ),
    ]
